#! /usr/bin/env python
#
# Copyright (C) 2017 Marco Barisione
#
# Released under the terms of the GNU LGPL license version 2.1 or later.

import os
import sys

_g_root_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
if os.path.exists(os.path.join(_g_root_dir, 'karton', 'program.py')):
    # Running from the source.
    sys.path.append(_g_root_dir)

from karton import program

if __name__ == '__main__':
    program.main_with_defaults()
