#! /usr/bin/env python
#
# Copyright (C) 2017 Marco Barisione
#
# Released under the terms of the GNU LGPL license version 2.1 or later.

from karton import karton

if __name__ == '__main__':
    karton.main_with_defaults()
